Image:
  zfsbootmenu_essential_binaries:
    # important base network
    - ip
    - dhclient
    - dhclient-script
    - sed
    - touch
    # The following for tailscale 
    - tailscale
    - tailscaled
    - getent
    - /usr/sbin/iptables*
    - /usr/sbin/ip6tables*
  zfsbootmenu_optional_binaries:
    # nice for network
    - ssh
    - nc 
    - ping
    - ping4
    - ping6
    - ss
  zfsbootmenu_essential_files:
    # The following for tailscale 
    - /var/lib/tailscale/tailscaled.state
  zfsbootmenu_essential_libraries:
    - xtables/*
  zfsbootmenu_essential_modules:
    - net/**/*.ko*
    - tun
    - ecb 
    - bridge 
    - stp 
    - llc 
    - ipv6 
    - bonding
    - 8021q 
    - ipvlan
    - macvlan
    - af_packet
    - virtio_net
    - xennet
Hooks:
  zfsbootmenu_preprompt: 
    - /zbm/contrib/recipes/net-tailscale/tailscale-start.sh
  zfsbootmenu_teardown:
    - /zbm/contrib/recipes/net-tailscale/tailscale-stop.sh
