# This is the base configuration
# The configuration fragments from various "recipes" are merged into this configuration and then sent to the generate-zbm
#
Global:
  # Note: The build container overrides Global.ManageImages
  ManageImages: true
  ImageDir: /tmp/zbm-image
Components:
  # Enable only current kernel/initramfs components and a backup
  Enabled: true
  Versions: false
  # The ZBM build container *forces* Components.ImageDir
  ImageDir: /tmp/zbm-image
EFI:
  # Enable only current EFI executable and a backup file
  Enabled: true
  Versions: false
  # Note: The ZBM build container *forces* EFI.ImageDir
  ImageDir: /tmp/zbm-image
Kernel:
  # Set ZBM command-line options for the EFI bundle here
  CommandLine: zfsbootmenu ro loglevel=7
